//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mylist
    {
        public int Id { get; set; }
        public string Des { get; set; }
        public string Time_now { get; set; }
    }
}
